algoritmo "Media"
// Função :
// Autor :
// Data : 04/03/2022
// Seção de Declarações 
var
   N1, N2: Inteiro
   M: Real
   Af: Caractere
inicio
      Escreva ("Eu irei fazer a média de dois números para você, ok? ")
      Leia (Af)
      Escreva ("Escreva o primeiro número: ")
      Leia (N1)
      Escreva ("Agora, escreva o segundo número: ")
      Leia (N2)
      M <- (N1 + N2) / 2
      Escreva ("O resultado da média de ", N1, " e ", N2, " é igual a ", M)
fimalgoritmo
